@SETLOCAL

@ECHO %~nx0

CHCP
@REM Seting UTF-8 encoding.
@REM CHCP 65001

CALL %env_qUtil%\exit_if_error

SET accumAssemblyPath=%1
IF [%accumAssemblyPath%] EQU [] GOTO BrokenInputParameter
IF [%accumAssemblyPath%] EQU [""] GOTO BrokenInputParameter


SET sqlScript=%accumAssemblyPath%\assemblies.register.sql

@REM Let's clear or create target script file.
TYPE NUL> %sqlScript%

@ECHO.>> %sqlScript%
@ECHO -- This script was generated by our build-server>> %sqlScript%
@ECHO.>> %sqlScript%



@GOTO :EOF

:BrokenInputParameter
ECHO  !#!  Interrupted. Not all input parameters have been set to call this script!
ECHO.
EXIT 1000